/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app_tecnical_arkive;

/**
 *
 * @author Andy
 */
public class Cadastrar_Empresa_Window extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar_Empresa_Window
     */
    public Cadastrar_Empresa_Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRegime = new javax.swing.ButtonGroup();
        buttonGroupPostoDeCombustivel = new javax.swing.ButtonGroup();
        buttonGroupModeloCalculo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeEmpresa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbSimples = new javax.swing.JRadioButton();
        rbPresumido = new javax.swing.JRadioButton();
        rbReal = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rbPostoCombustivelSim = new javax.swing.JRadioButton();
        rbPostoCombustivelNao = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfPIS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfIRPJ01 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfCOFINS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCSSL01 = new javax.swing.JTextField();
        tfIRPJ02 = new javax.swing.JTextField();
        tfCSSL02 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfValorHonorario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfDiaVencimento = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        xboxStatus = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        rbCalculo01 = new javax.swing.JRadioButton();
        rbCalculo02 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Empresa");

        jLabel1.setText("Empresa:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Regime"));

        buttonGroupRegime.add(rbSimples);
        rbSimples.setSelected(true);
        rbSimples.setText("Simples");
        rbSimples.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSimplesMouseClicked(evt);
            }
        });

        buttonGroupRegime.add(rbPresumido);
        rbPresumido.setText("Presumido");
        rbPresumido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPresumidoMouseClicked(evt);
            }
        });

        buttonGroupRegime.add(rbReal);
        rbReal.setText("Real");
        rbReal.setEnabled(false);
        rbReal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRealMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbSimples)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPresumido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbReal)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSimples)
                    .addComponent(rbReal)
                    .addComponent(rbPresumido))
                .addGap(46, 46, 46))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Posto de Combustível"));

        buttonGroupPostoDeCombustivel.add(rbPostoCombustivelSim);
        rbPostoCombustivelSim.setText("Sim");

        buttonGroupPostoDeCombustivel.add(rbPostoCombustivelNao);
        rbPostoCombustivelNao.setSelected(true);
        rbPostoCombustivelNao.setText("Não");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbPostoCombustivelSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPostoCombustivelNao)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPostoCombustivelSim)
                    .addComponent(rbPostoCombustivelNao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Alíquotas"));

        jLabel2.setText("PIS:");

        tfPIS.setText("0.65");
        tfPIS.setEnabled(false);

        jLabel3.setText("IRPJ:");

        tfIRPJ01.setText("1.2");
        tfIRPJ01.setEnabled(false);

        jLabel4.setText("COFINS:");

        tfCOFINS.setText("3");
        tfCOFINS.setEnabled(false);

        jLabel5.setText("CSSL:");

        tfCSSL01.setText("1.08");
        tfCSSL01.setEnabled(false);

        tfIRPJ02.setEnabled(false);

        tfCSSL02.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCOFINS)
                    .addComponent(tfPIS, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfIRPJ01)
                    .addComponent(tfCSSL01, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfIRPJ02, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(tfCSSL02))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfIRPJ01)
                        .addComponent(tfPIS)
                        .addComponent(tfIRPJ02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCOFINS)
                        .addComponent(tfCSSL01)
                        .addComponent(tfCSSL02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Valor do Honorário:");

        jLabel7.setText("Dia do Vencimento:");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Status da Empresa"));

        xboxStatus.setSelected(true);
        xboxStatus.setText("Ativo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xboxStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xboxStatus))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancelar");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo de Cálculo"));

        buttonGroupModeloCalculo.add(rbCalculo01);
        rbCalculo01.setSelected(true);
        rbCalculo01.setText("Cálculo I");
        rbCalculo01.setEnabled(false);
        rbCalculo01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbCalculo01MousePressed(evt);
            }
        });

        buttonGroupModeloCalculo.add(rbCalculo02);
        rbCalculo02.setText("Cálculo II");
        rbCalculo02.setEnabled(false);
        rbCalculo02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbCalculo02MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbCalculo01)
                .addGap(18, 18, 18)
                .addComponent(rbCalculo02))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCalculo01)
                    .addComponent(rbCalculo02))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeEmpresa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfValorHonorario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNomeEmpresa)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfValorHonorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSimplesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSimplesMouseClicked
        // TODO add your handling code here:
        tfPIS.setEnabled(false);
        tfCOFINS.setEnabled(false);
        tfCSSL01.setEnabled(false);
        tfIRPJ01.setEnabled(false);
        tfCSSL02.setEnabled(false);
        tfIRPJ02.setEnabled(false);
            
        rbCalculo01.setEnabled(false);
        rbCalculo02.setEnabled(false);
        rbCalculo01.setSelected(true);
            
        fRegime = "Simples";
    }//GEN-LAST:event_rbSimplesMouseClicked

    private void rbPresumidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPresumidoMouseClicked
        // TODO add your handling code here:
        tfPIS.setEnabled(true);
        tfCOFINS.setEnabled(true);
        tfCSSL01.setEnabled(true);
        tfIRPJ01.setEnabled(true);
        rbCalculo01.setEnabled(true);
        rbCalculo02.setEnabled(true);
        
        fRegime = "Presumido";
    }//GEN-LAST:event_rbPresumidoMouseClicked

    private void rbRealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRealMouseClicked
        // TODO add your handling code here:
        tfPIS.setEnabled(true);
        tfCOFINS.setEnabled(true);
        tfCSSL01.setEnabled(true);
        tfIRPJ01.setEnabled(true);
        
        rbCalculo01.setEnabled(true);
        rbCalculo02.setEnabled(true);
        
        fRegime = "Real";
    }//GEN-LAST:event_rbRealMouseClicked

    private void rbCalculo01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCalculo01MousePressed
        // TODO add your handling code here:
        tfCSSL02.setEnabled(false);
        tfIRPJ02.setEnabled(false);
        
        tfPIS.setText("0,65");
        tfCOFINS.setText("3");
        tfIRPJ01.setText("1,2");
        tfCSSL01.setText("1,08");
        
        
    }//GEN-LAST:event_rbCalculo01MousePressed

    private void rbCalculo02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCalculo02MousePressed
        // TODO add your handling code here:
        tfCSSL02.setEnabled(true);
        tfIRPJ02.setEnabled(true);
        
        tfPIS.setText("0,65");
        tfCOFINS.setText("3");
        tfIRPJ01.setText("12");
        tfIRPJ02.setText("9");
        tfCSSL01.setText("8");
        tfCSSL02.setText("15");
    }//GEN-LAST:event_rbCalculo02MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (rbSimples.isSelected()) {
            fRegime = "Simples";
        }else if (rbPresumido.isSelected()) {
            fRegime = "Presumido";
        }else if (rbReal.isSelected()) {
            fRegime = "Real";
        }
        
        if(rbPostoCombustivelSim.isSelected()){
            fPostoCombustivel = "Sim";
        }else if (rbPostoCombustivelNao.isSelected()) {
            fPostoCombustivel = "Não";
        }
        
        if (rbCalculo01.isSelected()) {
            fIRPJ_02 = "0";
            fCSSL_02 = "0";
        }else if(rbCalculo02.isSelected()){
            fIRPJ_02 = tfIRPJ02.getText();
            fCSSL_02 = tfCSSL02.getText();
        }
        
        if (xboxStatus.isSelected()) {
            fStatus = "Ativo";
        }
        
        ComfirmarDados enviarDados = new ComfirmarDados();
        enviarDados.setVisible(true);
        enviarDados.receberDadosCadastrais(tfNomeEmpresa.getText(), fRegime, fPostoCombustivel,
                tfPIS.getText(), tfCOFINS.getText(), tfIRPJ01.getText(), fIRPJ_02, tfCSSL01.getText(), 
                fCSSL_02, tfValorHonorario.getText(), tfDiaVencimento.getText(), fStatus);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_Empresa_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_Empresa_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_Empresa_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_Empresa_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar_Empresa_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupModeloCalculo;
    private javax.swing.ButtonGroup buttonGroupPostoDeCombustivel;
    private javax.swing.ButtonGroup buttonGroupRegime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton rbCalculo01;
    private javax.swing.JRadioButton rbCalculo02;
    private javax.swing.JRadioButton rbPostoCombustivelNao;
    private javax.swing.JRadioButton rbPostoCombustivelSim;
    private javax.swing.JRadioButton rbPresumido;
    private javax.swing.JRadioButton rbReal;
    private javax.swing.JRadioButton rbSimples;
    private javax.swing.JTextField tfCOFINS;
    private javax.swing.JTextField tfCSSL01;
    private javax.swing.JTextField tfCSSL02;
    private javax.swing.JTextField tfDiaVencimento;
    private javax.swing.JTextField tfIRPJ01;
    private javax.swing.JTextField tfIRPJ02;
    private javax.swing.JTextField tfNomeEmpresa;
    private javax.swing.JTextField tfPIS;
    private javax.swing.JTextField tfValorHonorario;
    private javax.swing.JCheckBox xboxStatus;
    // End of variables declaration//GEN-END:variables
    String fRegime, fPostoCombustivel, fIRPJ_02, fCSSL_02, fStatus;
}
